### ISSUE TITLE
operator keeps crashing when using cluster.yaml from quickstart

### ISSUE THREAD

**Issue by woutersmit** [Opster/opensearch-k8s-operator#174]
Not sure what i'm doing wrong, but the operator keeps crashing on me when using cluster.yaml from quickstart. It fails to setup a complete opensearch cluster.

Helm: opensearch-operator v1.0.2

Only change I made in the cluster.yaml was changing the persistence for 'masters' nodepool to emptyDir.

```
1.6542485097997456e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
1.6542485098001041e+09	INFO	setup	starting manager
1.6542485098004386e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
1.654248509800439e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
I0603 09:28:29.800487       1 leaderelection.go:248] attempting to acquire leader lease default/a867c7dc.opensearch.opster.io...
I0603 09:28:46.219922       1 leaderelection.go:258] successfully acquired lease default/a867c7dc.opensearch.opster.io
1.654248526219977e+09	DEBUG	events	Normal	{"object": {"kind":"ConfigMap","namespace":"default","name":"a867c7dc.opensearch.opster.io","uid":"c9e0c0e1-ebb2-4dbc-bf1d-8fae10d5553c","apiVersion":"v1","resourceVersion":"155303"}, "reason": "LeaderElection", "message": "opensearch-operator-controller-manager-5685878466-kww5s_4c7864db-b0fa-4237-af03-5bbeb358a6fa became leader"}
1.6542485262200863e+09	DEBUG	events	Normal	{"object": {"kind":"Lease","namespace":"default","name":"a867c7dc.opensearch.opster.io","uid":"d941714b-0fb2-4d7a-9295-2bc734e2ac60","apiVersion":"coordination.k8s.io/v1","resourceVersion":"155304"}, "reason": "LeaderElection", "message": "opensearch-operator-controller-manager-5685878466-kww5s_4c7864db-b0fa-4237-af03-5bbeb358a6fa became leader"}
1.65424852622022e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.OpenSearchCluster"}
1.6542485262202456e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Pod"}
1.6542485262202508e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Secret"}
1.654248526220254e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.ConfigMap"}
1.6542485262202568e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Service"}
1.6542485262202716e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.Deployment"}
1.6542485262202895e+09	INFO	controller.opensearchcluster	Starting EventSource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "source": "kind source: *v1.StatefulSet"}
1.6542485262203026e+09	INFO	controller.opensearchcluster	Starting Controller	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster"}
1.6542485263216e+09	INFO	controller.opensearchcluster	Starting workers	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "worker count": 1}
1.6542485263217413e+09	INFO	controller.opensearchcluster	Reconciling OpenSearchCluster	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "cluster": "default/my-first-cluster"}
1.6542485263384736e+09	INFO	controller.opensearchcluster	No security specified. Not doing anything	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6542485263408175e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6542485263416903e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-discovery", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.654248526342554e+09	DEBUG	controller.opensearchcluster	resource diff	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6542485263431313e+09	DEBUG	controller.opensearchcluster	updating resource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.654248526346031e+09	DEBUG	controller.opensearchcluster	resource updated	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6542485263551443e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-bootstrap-0", "namespace": "default", "apiVersion": "v1", "kind": "Pod"}
1.654248526356161e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-masters", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
panic: runtime error: index out of range [0] with length 0

goroutine 358 [running]:
opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).reconcileNodeStatefulSet(0xc00058cc40, {{0xc00011a8d5, 0x7}, 0x3, {0xc00011a8dc, 0x3}, {0xc0003ed2c0, 0xc0003ed2f0}, {0x0, 0x0}, ...}, ...)
	/workspace/pkg/reconcilers/cluster.go:145 +0xfec
opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).Reconcile(0xc00058cc40)
	/workspace/pkg/reconcilers/cluster.go:87 +0xc70
opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).reconcilePhaseRunning(0xc00018d540, {0x1b64018, 0xc0005b5e60})
	/workspace/controllers/opensearchController.go:326 +0x6ae
opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).Reconcile(0xc00018d540, {0x1b64018, 0xc0005b5e60}, {{{0xc0001b5036, 0x7}, {0xc0001b5050, 0x10}}})
	/workspace/controllers/opensearchController.go:141 +0x4be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0001d42c0, {0x1b64018, 0xc00041fe60}, {{{0xc0001b5036, 0x184b580}, {0xc0001b5050, 0x413a94}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001d42c0, {0x1b63f70, 0xc000621200}, {0x178ff00, 0xc0001359a0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001d42c0, {0x1b63f70, 0xc000621200})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by prudhvigodithi** [comment]
Hey @woutersmit thanks for reporting the bug, I see whats happening, the internal `Volume expansion logic` that periodically looks for disk size to scale if required, fails to ignore `emptyDir`.
I should be fixing this soon, meanwhile can you try without `emptyDir` ?
Thank you

**Comment by woutersmit** [comment]
Could 'hostPath' have the same issue, I have tried that as well..

**Comment by prudhvigodithi** [comment]
> Could 'hostPath' have the same issue, I have tried that as well..

Yes @woutersmit, the fix should ignore both `EmptyDir` and `HostPath`.

**Comment by idanl21** [comment]
So we need to add emptyDir and HostPath?  i though that we already added it, no @prudhvigodithi ?

**Comment by prudhvigodithi** [comment]
Hey @idanl21, yes we had it but the volume reconciler is breaking the operator when EmptyDir and HostPath is declared, this is a bug and needs to be fixed, where the volume reconciler should not looks for scaling when EmptyDir and HostPath is declared.

**Comment by dbason** [comment]
@prudhvigodithi can this issue be closed out?

**Comment by prudhvigodithi** [comment]
Hey @dbason yes this issue can be closed.
@woutersmit please install the latest version of helm and you should be able to use emptyDir or hostPath.
https://artifacthub.io/packages/helm/opensearch-operator/opensearch-operator
`helm install my-opensearch-operator opensearch-operator/opensearch-operator --version 1.0.3`

Closing this issue, please feel free to re-open.
Thank you
