### ISSUE TITLE
Make Operator compatible with OpenSearch 2.0.0.

### ISSUE THREAD

**Issue by prudhvigodithi** [Opster/opensearch-k8s-operator#176]
2.0.0 issues:
Security admin issue with using 9300
Error:
```
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to my-first-cluster.default.svc.cluster.local:9300 ... done
ERR: An unexpected RuntimeException occured: error while performing request
Trace:
java.lang.RuntimeException: error while performing request
	at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:932)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:307)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:295)
	at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:464)
	at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:161)
Caused by: org.apache.http.ProtocolException: Not a valid protocol version: This is not an HTTP port
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.http.ParseException: Not a valid protocol version: This is not an HTTP port
	at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:148)
	at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366)
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112)
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
	... 11 more

```

Dashboard 401 error:
```
217","userAgent":"kube-probe/1.22+"},"res":{"statusCode":401,"responseTime":1,"contentLength":9},"message":"GET /api/status 401 1ms - 9.0B"}
{"type":"log","@timestamp":"2022-05-27T00:01:30Z","tags":["info","plugins-system"],"pid":1,"message":"Stopping all plugins."}
```

Security admin job:
```
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-5 [ACTIVE]
   SUCC: Configuration for 'audit' created or updated
FAIL: 2 nodes reported failures. Failure is /{"_nodes":{"total":2,"successful":0,"failed":2,"failures":[{"type":"failed_node_exception","reason":"Failed node [43_zoSkxS1OA3GRh92QZQA]","node_id":"43_zoSkxS1OA3GRh92QZQA","caused_by":{"type":"static_resource_exception","reason":"static_resource_exception: Unable to load static tenants"}},{"type":"failed_node_exception","reason":"Failed node [1zIIefZiQuukCpF0Ptc1AA]","node_id":"1zIIefZiQuukCpF0Ptc1AA","caused_by":{"type":"static_resource_exception","reason":"Unable to load static tenants"}}]},"cluster_name":"my-first-cluster","configupdate_response":{"nodes":{},"node_size":0,"has_failures":true,"failures_size":2}}
FAIL: Expected 2 nodes to return response, but got 0
Done with failures
```

**Comment by ibotty** [comment]
This is the same as #123, isn't it?

**Comment by prudhvigodithi** [comment]
Hey @ibotty yes looks like its the same https://github.com/Opster/opensearch-k8s-operator/issues/123.

**Comment by prudhvigodithi** [comment]
More changes: 

`-cd` (Directory containing multiple security plugin configuration files.) path change from `/usr/share/opensearch/plugins/opensearch-security/securityconfig` to `/usr/share/opensearch/config/opensearch-security` 
`securityadmin.sh` -cd /usr/share/opensearch/config/opensearch-security`

Dashboard `ProbeHandler` `/api/status` pass `httpHeaders`, unlike before 2.x OpenSearch `/api/status` does not require authentication,  but with 2.x series requires  authentication.
Related issues
https://github.com/opensearch-project/security-dashboards-plugin/issues/945
https://github.com/opensearch-project/documentation-website/issues/563

**Comment by prudhvigodithi** [comment]
Hey should be consider operator to be be backward compatible ?
Example lets says we release a new version `v2.0` that is compatible to `2.x` versions, should it even work when users adds `1.3.x` version to the cluster yaml? or should it be only for `2.x` version ? thoughts ? 
@idanl21 @swoehrl-mw @segalziv @dbason

**Comment by rursprung** [comment]
i think it has to be - how else would you handle an upgrade of an existing cluster managed through the operator? and you want to be able to do canary upgrades, i.e. even after upgrading the operator you'll still have clusters running on the previous major release for a while.

**Comment by kfox1111** [comment]
+1 to cluster 1.x -> 2.x capabilities. Though this thread does raise a second feature. The ability to have parallel operator installs that watch only one namespace. That allows you to do canary upgrades of the operator without having to have an entirely separate k8s cluster.

**Comment by smlx** [comment]
Why are you trying to use 9300 as the REST port? Isn't 9300 usually the transport port?

**Comment by prudhvigodithi** [comment]
@smlx 1.x series of OpenSearch, from the document `securityadmin.sh` only works with 9300 as default but with 2.x the transport client was retired and recommended to use HTTP port.

**Comment by prudhvigodithi** [comment]
> I agree with @rursprung here. Backwards compatibility for the operator between major opensearch versions is a must so you can have clusters with different versions running at the same time and do major version upgrades.

Yes, I'm adding logic for the operator to work with (to be able to install with) both 1.x and 2.x as well, but as now https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#rolling-upgrades `Downgrades and upgrades that span more than one major version are not supported, as this will put the OpenSearch cluster in an unsupported state.`
