### ISSUE TITLE
When create cluster with master=1, Discovery problem.

### ISSUE THREAD

**Issue by chenyg0911** [Opster/opensearch-k8s-operator#203]
I try to create a cluster with 1 master, 1 data and 1 client.
operator deploy witch helm
 chart version : opensearch-operator-1.0.3  app verion: 1.16.0
cluster.yaml:
```
 apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: test-elk
  namespace: elk
spec:
  general:
    serviceName: test-elk
    version: 1.3.3
  nodePools:
    - component: masters
      replicas: 1
      diskSize: "5Gi"
      persistence:
        emptyDir: {}
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "master"
        # - "data"
    - component: datas
      replicas: 1
      diskSize: "5Gi"
      resources:
         requests:
            memory: "4Gi"
            cpu: "1000m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "data"
    - component: clients
      replicas: 1
      diskSize: "5Gi"
      persistence:
        emptyDir: {}
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "ingest"
```
pods running:
```
NAME                 READY   STATUS    RESTARTS   AGE
test-elk-clients-0   1/1     Running   0          30m
test-elk-datas-0     1/1     Running   0          30m
test-elk-masters-0   1/1     Running   0          30m

```
But all pod try to search the master.
curl the client service witch expose with service:
```
curl -u admin:admin -k https://client-service4:9200/_cat/nodes?v
{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
```
check the pod log:

master node log:
```
[2022-06-30T04:47:37,865][WARN ][o.o.c.c.ClusterFormationFailureHelper] [test-elk-masters-0] master not discovered or elected yet, an election requires a node with id [hRy0F7Q-TN23NsVPo04Iyg], have discovered [{test-elk-masters-0}{_vekf0bSRtmjJaWPjZG_ZQ}{0fCcqUWhT7a13ORJ38mIOA}{test-elk-masters-0}{10.233.96.98:9300}{m}{shard_indexing_pressure_enabled=true}] which is not a quorum; discovery will continue using [10.233.92.121:9300, 10.233.92.122:9300] from hosts providers and [{test-elk-bootstrap-0}{hRy0F7Q-TN23NsVPo04Iyg}{KIP0IvaqRn2u_SnN2uiiXA}{test-elk-bootstrap-0}{10.233.96.99:9300}{m}{shard_indexing_pressure_enabled=true}, {test-elk-masters-0}{_vekf0bSRtmjJaWPjZG_ZQ}{0fCcqUWhT7a13ORJ38mIOA}{test-elk-masters-0}{10.233.96.98:9300}{m}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 1, last-accepted version 18 in term 1
[2022-06-30T04:47:38,702][WARN ][o.o.c.NodeConnectionsService] [test-elk-masters-0] failed to connect to {test-elk-bootstrap-0}{hRy0F7Q-TN23NsVPo04Iyg}{KIP0IvaqRn2u_SnN2uiiXA}{test-elk-bootstrap-0}{10.233.96.99:9300}{m}{shard_indexing_pressure_enabled=true} (tried [49] times)
org.opensearch.transport.ConnectTransportException: [test-elk-bootstrap-0][10.233.96.99:9300] connect_timeout[30s]
        at org.opensearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:1070) ~[opensearch-1.3.3.jar:1.3.3]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733) ~[opensearch-1.3.3.jar:1.3.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

```
it seems the cluster node try to  elector with bootstrap pod which is terminated.

I've ttried create cluster with 3 master node, all nodes work fine.

**Comment by swoehrl-mw** [comment]
Hi @chenyg0911.
This is a known problem, the operator currently cannot handle single master deployments (see #100 for a possible workaround).

**Comment by chenyg0911** [comment]
Got it! Thanks @swoehrl-mw
