### ISSUE TITLE
Operator security: deploy with http certs only produce an error

### ISSUE THREAD

**Issue by elkh510** [Opster/opensearch-k8s-operator#223]
hi all
try to deploy next
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  confMgmt:
    VerUpdate: false
    autoScaler: false
    monitoring: true
    smartScaler: false
  general:
    serviceName: opensearch
    version: 2.0.1
    setVMMaxMapCount: true
    serviceName: opensearch
    httpPort: 9200
    additionalConfig:
      cluster.initial_master_nodes: opensearch-masters-0
      compatibility.override_main_response_version: "true"
      discovery.seed_hosts: opensearch-masters-0
  security:
    tls:
      http:
        generate: false
        secret:
          name: elasticsearch-server-cert
      transport:
        generate: true
  dashboards:
    enable: false
    version: 2.0.1
    replicas: 1
  nodePools:
    - component: masters
      replicas: 1
      resources:
        limits:
          cpu: 1100m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1536Mi
      jvm: "-Xmx1024M -Xms1024M"
      roles:
        - "data"
        - "master"
      diskSize: "16Gi"
      persistence:
        pvc:
          storageClass: "ssd"
          accessModes: [ReadWriteOnce]
```
and get error
```
[2022-07-18T14:07:15,031][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [opensearch-masters-0] Exception while retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, AUDIT] (index=.opendistro_security)
org.opensearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
	at org.opensearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:204) ~[opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:190) ~[opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:81) ~[opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:58) ~[opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:204) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) [opensearch-index-management-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:240) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:157) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) [opensearch-performance-analyzer-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:174) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:102) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:423) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.client.support.AbstractClient.multiGet(AbstractClient.java:539) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.security.configuration.ConfigurationLoaderSecurity7.loadAsync(ConfigurationLoaderSecurity7.java:211) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.configuration.ConfigurationLoaderSecurity7.load(ConfigurationLoaderSecurity7.java:102) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.configuration.ConfigurationRepository.getConfigurationsFromIndex(ConfigurationRepository.java:375) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.configuration.ConfigurationRepository.reloadConfiguration0(ConfigurationRepository.java:321) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.configuration.ConfigurationRepository.reloadConfiguration(ConfigurationRepository.java:306) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.configuration.ConfigurationRepository$1.run(ConfigurationRepository.java:166) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	
____________
[2022-07-18T14:07:23,050][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [opensearch-masters-0] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, AUDIT] (index=.opendistro_security)

```

how this can be resolved ?

**Comment by dbason** [comment]
I think @prudhvigodithi has been working on the 2.0.0 support - I wonder if this has been fixed in his work

**Comment by prudhvigodithi** [comment]
Hey @elkh510 can you try with latest helm chart and update us?
`helm install opensearch-operator opensearch-operator/opensearch-operator --version 2.0.0`
also can you share the yaml file of `elasticsearch-server-cert`, so that I will try to replicate from my end.
Thank you

**Comment by dbason** [comment]
Out of interest why are you setting the initial masters manually?  This is all part of the operator setting up a cluster.  I'm not convinced it's causing the issue, but it might be worthwhile removing that.

**Comment by elkh510** [comment]
>why are you setting the initial masters manually?

we need opensearch in single-node https://github.com/Opster/opensearch-k8s-operator/issues/100

>I'm not convinced it's causing the issue, but it might be worthwhile removing that.

same error

**Comment by idanl21** [comment]
Hey @elkh510, still facing the issue ?
