### ISSUE TITLE
Recreate cluster with existing data

### ISSUE THREAD

**Issue by dickescheid** [Opster/opensearch-k8s-operator#261]
Assuming I lose my kubernetes cluster and need to redeploy, but I still have the disk snapshots with which I can recreate the persistent volumes and all my data.

How can I achieve this? Currently if I deploy a cluster, delete the cluster `kubectl delete -f cluster.yaml` leaving the PVCs untouched, and reapply the `cluster.yaml` file, the nodes will not spin up.

Here are the log files:

```
[2022-08-19T10:03:45,494][INFO ][o.o.c.c.JoinHelper       ] [testos2-masters-0] failed to join {testos2-bootstrap-0}{SQpJZ3nlSmmx7qNuYmdxxg}{HYxA9wW9SQupWDGLN_DXbw}{testos2-bootstrap-0}{10.92.4.233:9300}{m}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={testos2-masters-0}{XG6XWKeBQ76eCKVXcu9r4w}{bChf8rr7TuO6rF8nl7eddA}{testos2-masters-0}{10.92.1.5:9300}{dm}{shard_indexing_pressure_enabled=true}, minimumTerm=3, optionalJoin=Optional.empty}
org.opensearch.transport.RemoteTransportException: [testos2-bootstrap-0][10.92.4.233:9300][internal:cluster/coordination/join]
Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
        at org.opensearch.cluster.coordination.Coordinator$2.onFailure(Coordinator.java:631) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:72) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.security.transport.SecurityInterceptor$RestoringTransportResponseHandler.handleException(SecurityInterceptor.java:308) ~[?:?]
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1357) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:415) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:733) ~[opensearch-1.3.0.jar:1.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opensearch.transport.RemoteTransportException: [testos2-masters-0][10.92.1.5:9300][internal:cluster/coordination/join/validate]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid eRwLHPd0RKSUkA-GR90B1g than local cluster uuid OH6GOfilQXSleXGROb7KCg, rejecting
        at org.opensearch.cluster.coordination.JoinHelper.lambda$new$5(JoinHelper.java:213) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceivedDecorate(SecuritySSLRequestHandler.java:193) ~[?:?]
        at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:336) ~[?:?]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:153) ~[?:?]
        at org.opensearch.security.OpenSearchSecurityPlugin$7$1.messageReceived(OpenSearchSecurityPlugin.java:647) ~[?:?]
        at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:118) ~[?:?]
        at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:91) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:443) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:792) ~[opensearch-1.3.0.jar:1.3.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) ~[opensearch-1.3.0.jar:1.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by idanl21** [comment]
Hey @dickescheid, not sure about that issue, never tried that.
I believe that you will have to create the new PVCs in the same prefix as the old ones, and also create the cluster with that prefix. also, I think that you need to delete master PVCs and keep only data.
keep in touch

**Comment by idanl21** [comment]
closing that issue, lets talk on the updated one

**Comment by mohammadzahid525** [comment]
Is this issue resolved? 
I seems to be facing exactly same issue.

**Comment by swoehrl-mw** [comment]
> Is this issue resolved? I seems to be facing exactly same issue.

Hi @mohammadzahid525. This is not yet fixed. We have an open PR (#366) that should also allow recreating clusters with existing PVCs. The relevant issue is #289.
