### ISSUE TITLE
Issue in bringing cluster with securityconfig

### ISSUE THREAD

**Issue by ervikrant06** [Opster/opensearch-k8s-operator#332]
I have gone through the bugs reported in past, but couldn't locate the one matching my issue. Bringing cluster without TLS support works fine. While trying to use securityconfig and TLS - setup is not coming up properly. one of the data node always stay in starting state. ex: testcluster-nodes-1 

~~~
$ kubectl get pod
NAME                                      READY   STATUS      RESTARTS   AGE
testcluster-dashboards-5956dd7d4c-bcnqp   1/1     Running     0          16m
testcluster-masters-0                     1/1     Running     0          16m
testcluster-nodes-0                       1/1     Running     0          16m
testcluster-nodes-1                       0/1     Running     0          13m
testcluster-securityconfig-update-xtwkw   0/1     Completed   0          16m
~~~

Conf I am using 

~~~
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: testcluster
  namespace: opensearch-mvp
spec:
  general:
    version: 2.3.0
    httpPort: 9200
    vendor: opensearch
    serviceName: testcluster
    setVMMaxMapCount: true
  dashboards:
    version: 2.3.0
    enable: true
    tls:
      enable: true
      generate: true
    replicas: 1
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  security:
    config:
      securityConfigSecret:
##Pre create this secret with required security configs, to override the default settings
       name: securityconfig-secret
    tls:
      transport:
        generate: true
        perNode: true
      http:
        generate: true
  nodePools:
    - component: masters
      replicas: 1
      diskSize: "10Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
    - component: nodes
      replicas: 2
      diskSize: "20Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
~~~

secrets got created.

~~~
$ kubectl get secret
NAME                          TYPE                                  DATA   AGE
default-token-zwlr6           kubernetes.io/service-account-token   3      130m
securityconfig-secret         Opaque                                1      61m
testcluster-admin-cert        kubernetes.io/tls                     3      24m
testcluster-admin-password    Opaque                                1      24m
testcluster-ca                Opaque                                2      24m
testcluster-dashboards-cert   Opaque                                3      24m
testcluster-http-cert         kubernetes.io/tls                     3      24m
testcluster-transport-cert    Opaque                                9      24m
~~~

Warnings from master node

~~~
[2022-10-21T10:47:44,292][WARN ][o.o.c.c.ClusterFormationFailureHelper] [testcluster-masters-0] cluster-manager not discovered or elected yet, an election requires a node with id [ZUynceMDT1etwRRs-eb3Ew], have discovered [{testcluster-masters-0}{kG35N6IIRRGsEhNxhQVC3Q}{x-0YddICRieiJsgbuVYC9A}{testcluster-masters-0}{172.22.1.106:9300}{dm}{shard_indexing_pressure_enabled=true}] which is not a quorum; discovery will continue using [172.22.1.110:9300, 172.22.1.83:9300] from hosts providers and [{testcluster-bootstrap-0}{ZUynceMDT1etwRRs-eb3Ew}{IrJuHb8oRH2G5e0i7e0GUA}{testcluster-bootstrap-0}{172.22.1.98:9300}{m}{shard_indexing_pressure_enabled=true}, {testcluster-masters-0}{kG35N6IIRRGsEhNxhQVC3Q}{x-0YddICRieiJsgbuVYC9A}{testcluster-masters-0}{172.22.1.106:9300}{dm}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 1, last-accepted version 31 in term 1
[2022-10-21T10:47:54,293][WARN ][o.o.c.c.ClusterFormationFailureHelper] [testcluster-masters-0] cluster-manager not discovered or elected yet, an election requires a node with id [ZUynceMDT1etwRRs-eb3Ew], have discovered [{testcluster-masters-0}{kG35N6IIRRGsEhNxhQVC3Q}{x-0YddICRieiJsgbuVYC9A}{testcluster-masters-0}{172.22.1.106:9300}{dm}{shard_indexing_pressure_enabled=true}] which is not a quorum; discovery will continue using [172.22.1.110:9300, 172.22.1.83:9300] from hosts providers and [{testcluster-bootstrap-0}{ZUynceMDT1etwRRs-eb3Ew}{IrJuHb8oRH2G5e0i7e0GUA}{testcluster-bootstrap-0}{172.22.1.98:9300}{m}{shard_indexing_pressure_enabled=true}, {testcluster-masters-0}{kG35N6IIRRGsEhNxhQVC3Q}{x-0YddICRieiJsgbuVYC9A}{testcluster-masters-0}{172.22.1.106:9300}{dm}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 1, last-accepted version 31 in term 1
~~~

error reported data-node-1

~~~
[2022-10-21T10:49:02,208][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [testcluster-nodes-1] Exception while retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
org.opensearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
        at org.opensearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:204) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:190) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:81) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:58) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) [opensearch-index-management-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:232) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:149) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) [opensearch-performance-analyzer-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:426) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.support.AbstractClient.multiGet(AbstractClient.java:542) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.security.configuration.ConfigurationLoaderSecurity7.loadAsync(ConfigurationLoaderSecurity7.java:207) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationLoaderSecurity7.load(ConfigurationLoaderSecurity7.java:98) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository.getConfigurationsFromIndex(ConfigurationRepository.java:372) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository.reloadConfiguration0(ConfigurationRepository.java:318) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository.reloadConfiguration(ConfigurationRepository.java:303) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository$1.run(ConfigurationRepository.java:163) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-10-21T10:49:04,168][WARN ][o.o.c.c.ClusterFormationFailureHelper] [testcluster-nodes-1] cluster-manager not discovered yet: have discovered [{testcluster-nodes-1}{4TDh6bqHQiW7QEPZAaiIPA}{VpzMR_ypTkaCk0201VyEgg}{testcluster-nodes-1}{172.22.1.83:9300}{d}{shard_indexing_pressure_enabled=true}, {testcluster-masters-0}{kG35N6IIRRGsEhNxhQVC3Q}{x-0YddICRieiJsgbuVYC9A}{testcluster-masters-0}{172.22.1.106:9300}{dm}{shard_indexing_pressure_enabled=true}]; discovery will continue using [172.22.1.110:9300, 172.22.1.106:9300] from hosts providers and [] from last-known cluster state; node term 0, last-accepted version 0 in term 0
~~~

**Comment by ervikrant06** [comment]
@prudhvigodithi Hello, I noticed in past you helped on similar issue in couple of bugs.

**Comment by idanl21** [comment]
Did you pre-created the securityconfig-secret secret?

**Comment by swoehrl-mw** [comment]
Without having looked at it in detail, could the problem be that there is only one cluster_manager node configured?

**Comment by ervikrant06** [comment]
securityconfig-secret.yaml

~~~
apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
type: Opaque
stringData:
      action_groups.yml: |-
         _meta:
           type: "actiongroups"
           config_version: 2
      internal_users.yml: |-
        _meta:
          type: "internalusers"
          config_version: 2
        admin:
          hash: "$2y$12$lJsHWchewGVcGlYgE3js/O4bkTZynETyXChAITarCHLz8cuaueIyq"
          reserved: true
          backend_roles:
          - "admin"
          description: "Demo admin user"
        dashboarduser:
          hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
          reserved: true
          description: "Demo OpenSearch Dashboards user"
      nodes_dn.yml: |-
        _meta:
          type: "nodesdn"
          config_version: 2
      whitelist.yml: |-
        _meta:
          type: "whitelist"
          config_version: 2
      tenants.yml: |-
        _meta:
          type: "tenants"
          config_version: 2
      roles_mapping.yml: |-
        _meta:
          type: "rolesmapping"
          config_version: 2
        all_access:
          reserved: false
          backend_roles:
          - "admin"
          description: "Maps admin to all_access"
        own_index:
          reserved: false
          users:
          - "*"
          description: "Allow full access to an index named like the username"
        readall:
          reserved: false
          backend_roles:
          - "readall"
        manage_snapshots:
          reserved: false
          backend_roles:
          - "snapshotrestore"
        dashboard_server:
          reserved: true
          users:
          - "dashboarduser"
      roles.yml: |-
        _meta:
          type: "roles"
          config_version: 2
        dashboard_read_only:
          reserved: true
        security_rest_api_access:
          reserved: true
        # Allows users to view monitors, destinations and alerts
        alerting_read_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/alerting/alerts/get'
            - 'cluster:admin/opendistro/alerting/destination/get'
            - 'cluster:admin/opendistro/alerting/monitor/get'
            - 'cluster:admin/opendistro/alerting/monitor/search'
        # Allows users to view and acknowledge alerts
        alerting_ack_alerts:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/alerting/alerts/*'
        # Allows users to use all alerting functionality
        alerting_full_access:
          reserved: true
          cluster_permissions:
            - 'cluster_monitor'
            - 'cluster:admin/opendistro/alerting/*'
          index_permissions:
            - index_patterns:
                - '*'
              allowed_actions:
                - 'indices_monitor'
                - 'indices:admin/aliases/get'
                - 'indices:admin/mappings/get'
        # Allow users to read Anomaly Detection detectors and results
        anomaly_read_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/ad/detector/info'
            - 'cluster:admin/opendistro/ad/detector/search'
            - 'cluster:admin/opendistro/ad/detectors/get'
            - 'cluster:admin/opendistro/ad/result/search'
            - 'cluster:admin/opendistro/ad/tasks/search'
            - 'cluster:admin/opendistro/ad/detector/validate'
            - 'cluster:admin/opendistro/ad/result/topAnomalies'
        # Allows users to use all Anomaly Detection functionality
        anomaly_full_access:
          reserved: true
          cluster_permissions:
            - 'cluster_monitor'
            - 'cluster:admin/opendistro/ad/*'
          index_permissions:
            - index_patterns:
                - '*'
              allowed_actions:
                - 'indices_monitor'
                - 'indices:admin/aliases/get'
                - 'indices:admin/mappings/get'
        # Allows users to read Notebooks
        notebooks_read_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/notebooks/list'
            - 'cluster:admin/opendistro/notebooks/get'
        # Allows users to all Notebooks functionality
        notebooks_full_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/notebooks/create'
            - 'cluster:admin/opendistro/notebooks/update'
            - 'cluster:admin/opendistro/notebooks/delete'
            - 'cluster:admin/opendistro/notebooks/get'
            - 'cluster:admin/opendistro/notebooks/list'
        # Allows users to read observability objects
        observability_read_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opensearch/observability/get'
        # Allows users to all Observability functionality
        observability_full_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opensearch/observability/create'
            - 'cluster:admin/opensearch/observability/update'
            - 'cluster:admin/opensearch/observability/delete'
            - 'cluster:admin/opensearch/observability/get'
        # Allows users to read and download Reports
        reports_instances_read_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/reports/instance/list'
            - 'cluster:admin/opendistro/reports/instance/get'
            - 'cluster:admin/opendistro/reports/menu/download'
        # Allows users to read and download Reports and Report-definitions
        reports_read_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/reports/definition/get'
            - 'cluster:admin/opendistro/reports/definition/list'
            - 'cluster:admin/opendistro/reports/instance/list'
            - 'cluster:admin/opendistro/reports/instance/get'
            - 'cluster:admin/opendistro/reports/menu/download'
        # Allows users to all Reports functionality
        reports_full_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/reports/definition/create'
            - 'cluster:admin/opendistro/reports/definition/update'
            - 'cluster:admin/opendistro/reports/definition/on_demand'
            - 'cluster:admin/opendistro/reports/definition/delete'
            - 'cluster:admin/opendistro/reports/definition/get'
            - 'cluster:admin/opendistro/reports/definition/list'
            - 'cluster:admin/opendistro/reports/instance/list'
            - 'cluster:admin/opendistro/reports/instance/get'
            - 'cluster:admin/opendistro/reports/menu/download'
        # Allows users to use all asynchronous-search functionality
        asynchronous_search_full_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/asynchronous_search/*'
          index_permissions:
            - index_patterns:
                - '*'
              allowed_actions:
                - 'indices:data/read/search*'
        # Allows users to read stored asynchronous-search results
        asynchronous_search_read_access:
          reserved: true
          cluster_permissions:
            - 'cluster:admin/opendistro/asynchronous_search/get'
        # Allows user to use all index_management actions - ism policies, rollups, transforms
        index_management_full_access:
          reserved: true
          cluster_permissions:
            - "cluster:admin/opendistro/ism/*"
            - "cluster:admin/opendistro/rollup/*"
            - "cluster:admin/opendistro/transform/*"
          index_permissions:
            - index_patterns:
                - '*'
              allowed_actions:
                - 'indices:admin/opensearch/ism/*'
        # Allows users to use all cross cluster replication functionality at leader cluster
        cross_cluster_replication_leader_full_access:
          reserved: true
          index_permissions:
            - index_patterns:
                - '*'
              allowed_actions:
                - "indices:admin/plugins/replication/index/setup/validate"
                - "indices:data/read/plugins/replication/changes"
                - "indices:data/read/plugins/replication/file_chunk"
        # Allows users to use all cross cluster replication functionality at follower cluster
        cross_cluster_replication_follower_full_access:
          reserved: true
          cluster_permissions:
            - "cluster:admin/plugins/replication/autofollow/update"
          index_permissions:
            - index_patterns:
                - '*'
              allowed_actions:
                - "indices:admin/plugins/replication/index/setup/validate"
                - "indices:data/write/plugins/replication/changes"
                - "indices:admin/plugins/replication/index/start"
                - "indices:admin/plugins/replication/index/pause"
                - "indices:admin/plugins/replication/index/resume"
                - "indices:admin/plugins/replication/index/stop"
                - "indices:admin/plugins/replication/index/update"
                - "indices:admin/plugins/replication/index/status_check"
      config.yml: |-
        _meta:
          type: "config"
          config_version: "2"
        config:
          dynamic:
            http:
              anonymous_auth_enabled: false
            authc:
              basic_internal_auth_domain:
                http_enabled: true
                transport_enabled: true
                order: "4"
                http_authenticator:
                  type: basic
                  challenge: true
                authentication_backend:
                  type: intern
~~~

data-node-1 remains in 0/1 state. 

`~~~
$ kubectl get pod
NAME                                      READY   STATUS      RESTARTS   AGE
testcluster-dashboards-5956dd7d4c-w9cgv   1/1     Running     0          4m30s
testcluster-masters-0                     1/1     Running     0          4m34s
testcluster-nodes-0                       1/1     Running     0          4m34s
testcluster-nodes-1                       0/1     Running     0          2m
~~~

On master 

~~~
[2022-10-25T10:11:05,001][WARN ][o.o.c.c.ClusterFormationFailureHelper] [testcluster-masters-0] cluster-manager not discovered or elected yet, an election requires a node with id [36m2MxFQR4WafmsGaVZiuQ], have discovered [{testcluster-masters-0}{ELaojHfuQxOmKyXCbRKQEw}{-d-QKd0FT7KTODQasYbjKA}{testcluster-masters-0}{172.22.1.88:9300}{dm}{shard_indexing_pressure_enabled=true}] which is not a quorum; discovery will continue using [172.22.1.84:9300, 172.22.1.96:9300] from hosts providers and [{testcluster-bootstrap-0}{36m2MxFQR4WafmsGaVZiuQ}{77zHmTWdS-WjTGhOUNLYXg}{testcluster-bootstrap-0}{172.22.1.78:9300}{m}{shard_indexing_pressure_enabled=true}, {testcluster-masters-0}{ELaojHfuQxOmKyXCbRKQEw}{-d-QKd0FT7KTODQasYbjKA}{testcluster-masters-0}{172.22.1.88:9300}{dm}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 1, last-accepted version 31 in term 1
~~~

**Comment by ervikrant06** [comment]
thanks, ya it looks to be the issue single master vs three master. With 3 masters it came up .. 

Do we have any example passing the custom certs?

**Comment by ervikrant06** [comment]
@swoehrl-mw thanks. 

Need some help with How To question 

Following services are created .. how can we create service of LoadBalancer type from cluster creation?

~~~
$ kubectl get svc
NAME                       TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)                               AGE
testcluster                ClusterIP   xx.xx.xx   <none>        9200/TCP,9300/TCP,9600/TCP,9650/TCP   79s
testcluster-coordinators   ClusterIP   None              <none>        9200/TCP,9300/TCP                     47s
testcluster-dashboards     ClusterIP   xx.xx.xx.xx   <none>        5601/TCP                              46s
testcluster-discovery      ClusterIP   None              <none>        9300/TCP                              47s
testcluster-masters        ClusterIP   None              <none>        9200/TCP,9300/TCP                     47s
testcluster-nodes          ClusterIP   None              <none>        9200/TCP,9300/TCP                     47s
~~~

serviceName is the only key present in CRD definition of opensearch cluster.

**Comment by swoehrl-mw** [comment]
@ervikrant06 The operator has no integrated support for configuring loadbalancers. You will need to create the service object yourself using one of the automatically created services as a template. Which one to choose depends on if you want to expose all your nodes (then use testcluster-nodes) or maybe only the coordinators (then use testcluster-coordinators). The difference is in the selector.

> Also we have used earlier in ES k8s operator which provide the functionality of customizing the service external DNS name (suffix)

How you expose the your opensearch cluster outside the kubernetes cluster is up to you and not handled by the operator (you can create a Loadbalancer or an Ingress).

As the original problem of this issue is solved, I'll close this issue. If you have further questions please feel free to use the [discussions section](https://github.com/Opster/opensearch-k8s-operator/discussions).
