### ISSUE TITLE
Operator fails to provision Opensearch 2.3.0 clusters

### ISSUE THREAD

**Issue by albgus** [Opster/opensearch-k8s-operator#337]
Hello,

For some reason when attempting to deploy OpenSearch 2.x, the bootstrap process doesn't work correctly. After some trial and error I've discovered that it works with 1.3.0 where the operator creates a bootstrap Pod when the cluster is created, but this doesn't happen when creating a 2.3.0 cluster, leaving the nodes unable to form a cluster.

### Environment

* Operator: 2.1.0
* OpenSearch: 2.3.0
* Kubernetes: EKS 1.23

### Manifest
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: test-cluster
  namespace: opensearch
spec:
  general:
    version: 1.3.0
    httpPort: 9200
    vendor: opensearch
    serviceName: test-cluster
    pluginsList: ["repository-s3"]
  dashboards:
    version: 1.3.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "256Mi"
         cpu: "50m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  security:
    config:
      securityConfigSecret:
       name: securityconfig-secret
    tls:
      transport:
        generate: true
      http:
        generate: true
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "20Gi"
      NodeSelector:
      resources:
         requests:
            memory: "1Gi"
            cpu: "100m"
         limits:
            memory: "2Gi"
      roles:
        - "master"
        - "data"
        - "ingest"
```

### Logs
For 1.3.0 all Pods seems to be created correctly:
```
$ k get pods
NAME                                       READY   STATUS      RESTARTS   AGE
test-cluster-bootstrap-0                   1/1     Running     0          3m3s
test-cluster-dashboards-8477d87d8f-lvg66   1/1     Running     0          3m2s
test-cluster-nodes-0                       1/1     Running     0          3m2s
test-cluster-nodes-1                       0/1     Running     0          46s
test-cluster-securityconfig-update-fw95z   0/1     Completed   0          3m3s
```

While for 2.3.0 the bootstrap pod is never created halting the deployment:
```
$ k get pods
NAME                                       READY   STATUS    RESTARTS   AGE
test-cluster-dashboards-6d67c8cc7b-8znjc   0/1     Running   0          2m32s
test-cluster-nodes-0                       0/1     Running   0          2m32s
```

Logs from test-cluster-nodes-0:
```
[2022-10-27T08:34:29,213][INFO ][o.o.n.Node               ] [test-cluster-masters-0] initialized
[2022-10-27T08:34:29,214][INFO ][o.o.n.Node               ] [test-cluster-masters-0] starting ...
[2022-10-27T08:34:29,452][INFO ][o.o.t.TransportService   ] [test-cluster-masters-0] publish_address {test-cluster-masters-0/10.60.130.103:9300}, bound_addresses {[::]:9300}
[2022-10-27T08:34:29,721][INFO ][o.o.b.BootstrapChecks    ] [test-cluster-masters-0] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2022-10-27T08:34:29,752][INFO ][o.o.c.c.ClusterBootstrapService] [test-cluster-masters-0] skipping cluster bootstrapping as local node does not match bootstrap requirements: [test-cluster-bootstrap-0]
[2022-10-27T08:34:39,756][WARN ][o.o.c.c.ClusterFormationFailureHelper] [test-cluster-masters-0] cluster-manager not discovered yet, this node has not previously joined a bootstrapped cluster, and this node must discover cluster-manager-eligible nodes [test-cluster-bootstrap-0] to bootstrap a cluster: have discovered [{test-cluster-masters-0}{w-uVpAA_QGe11CftKsKcxA}{EFRRaPOmSGag-vOQPNDWMA}{test-cluster-masters-0}{10.60.130.103:9300}{dim}{shard_indexing_pressure_enabled=true}]; discovery will continue using [10.60.130.104:9300] from hosts providers and [{test-cluster-masters-0}{w-uVpAA_QGe11CftKsKcxA}{EFRRaPOmSGag-vOQPNDWMA}{test-cluster-masters-0}{10.60.130.103:9300}{dim}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2022-10-27T08:34:49,759][WARN ][o.o.c.c.ClusterFormationFailureHelper] [test-cluster-masters-0] cluster-manager not discovered yet, this node has not previously joined a bootstrapped cluster, and this node must discover cluster-manager-eligible nodes [test-cluster-bootstrap-0] to bootstrap a cluster: have discovered [{test-cluster-masters-0}{w-uVpAA_QGe11CftKsKcxA}{EFRRaPOmSGag-vOQPNDWMA}{test-cluster-masters-0}{10.60.130.103:9300}{dim}{shard_indexing_pressure_enabled=true}]; discovery will continue using [10.60.130.104:9300] from hosts providers and [{test-cluster-masters-0}{w-uVpAA_QGe11CftKsKcxA}{EFRRaPOmSGag-vOQPNDWMA}{test-cluster-masters-0}{10.60.130.103:9300}{dim}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2022-10-27T08:34:59,760][WARN ][o.o.c.c.ClusterFormationFailureHelper] [test-cluster-masters-0] cluster-manager not discovered yet, this node has not previously joined a bootstrapped cluster, and this node must discover cluster-manager-eligible nodes [test-cluster-bootstrap-0] to bootstrap a cluster: have discovered [{test-cluster-masters-0}{w-uVpAA_QGe11CftKsKcxA}{EFRRaPOmSGag-vOQPNDWMA}{test-cluster-masters-0}{10.60.130.103:9300}{dim}{shard_indexing_pressure_enabled=true}]; discovery will continue using [10.60.130.104:9300] from hosts providers and [{test-cluster-masters-0}{w-uVpAA_QGe11CftKsKcxA}{EFRRaPOmSGag-vOQPNDWMA}{test-cluster-masters-0}{10.60.130.103:9300}{dim}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2022-10-27T08:34:59,763][WARN ][o.o.n.Node               ] [test-cluster-masters-0] timed out while waiting for initial discovery state - timeout: 30s
[2022-10-27T08:34:59,784][INFO ][o.o.h.AbstractHttpServerTransport] [test-cluster-masters-0] publish_address {test-cluster-masters-0/10.60.130.103:9200}, bound_addresses {[::]:9200}
[2022-10-27T08:34:59,785][INFO ][o.o.n.Node               ] [test-cluster-masters-0] started
[2022-10-27T08:34:59,785][INFO ][o.o.s.OpenSearchSecurityPlugin] [test-cluster-masters-0] Node started
[2022-10-27T08:34:59,786][INFO ][o.o.s.c.ConfigurationRepository] [test-cluster-masters-0] Will not attempt to create index .opendistro_security and default configs if they are absent. Use securityadmin to initialize cluster
[2022-10-27T08:34:59,787][INFO ][o.o.s.OpenSearchSecurityPlugin] [test-cluster-masters-0] 0 OpenSearch Security modules loaded so far: []
[2022-10-27T08:34:59,792][INFO ][o.o.s.c.ConfigurationRepository] [test-cluster-masters-0] Background init thread started. Install default config?: false
[2022-10-27T08:34:59,806][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [test-cluster-masters-0] Exception while retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
org.opensearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
        at org.opensearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:204) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:190) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:81) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.get.TransportMultiGetAction.doExecute(TransportMultiGetAction.java:58) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) [opensearch-index-management-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) [opensearch-performance-analyzer-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:232) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:149) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:426) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.client.support.AbstractClient.multiGet(AbstractClient.java:542) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.security.configuration.ConfigurationLoaderSecurity7.loadAsync(ConfigurationLoaderSecurity7.java:207) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationLoaderSecurity7.load(ConfigurationLoaderSecurity7.java:98) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository.getConfigurationsFromIndex(ConfigurationRepository.java:372) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository.reloadConfiguration0(ConfigurationRepository.java:318) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository.reloadConfiguration(ConfigurationRepository.java:303) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at org.opensearch.security.configuration.ConfigurationRepository$1.run(ConfigurationRepository.java:163) [opensearch-security-2.3.0.0.jar:2.3.0.0]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by albgus** [comment]
Also tried updating a 1.3.0 cluster to 2.3.0, but absolutely nothing happens. No update starts and there's absolutely zero logs from the operator (though that's probably because it doesn't seem to log anything at all anyway) . Possibly related to #311

**Comment by ervikrant06** [comment]
you may try to change the role from "master" to "cluster_manager". Also have you created a k8s secret referring https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/examples/securityconfig-secret.yaml

**Comment by swoehrl-mw** [comment]
Hi @albgus. 
As @ervikrant06 stated changing the role to `cluster_manager` should bring up the bootstrap pod (there is internal detection logic in the operator whether a bootstrap pod is needed and that has some problems when the master/cluster_manager role is used with the wrong major version).

> Also tried updating a 1.3.0 cluster to 2.3.0, but absolutely nothing happens...

Yes, this is likely related to the bug you linked, there is already a PR open for it. 
Regarding logs: Did you perchance check the kube-proxy container of the operator pod? Because the operator has quite a lot of logs normally.

**Comment by swoehrl-mw** [comment]
> This actually seems to have worked!

Great, I'll close this issue as resolved then.

> Though I have to admit that this seems very strange; I haven't seen this changed mentioned in any of the release notes of OpenSearch. This kind of breaking change seems like something worth communicating.

It's not a problem or change within opensearch but just within the operator because it has to handle both 1.x and 2.x versions at the same time and using the role name of the other version confuses some internal logic.
