### ISSUE TITLE
Cluster won't work with self-signed certificates

### ISSUE THREAD

**Issue by mastercrys** [Opster/opensearch-k8s-operator#365]
HI, i'm trying to deploy a cluster with one certificate for all nodes but nodes won't start successfully and this is the state of the pod:
```
opensearch-cluster-bootstrap-0                   1/1     Running             
opensearch-cluster-coordinating-0                0/1     Running             
opensearch-cluster-dashboards-5498f4fcbd-m4rgc   0/1     Running             
opensearch-cluster-masters-0                     0/1     Running             
opensearch-cluster-warm-0                        0/1     Running             
```

This is the cluster YAML file (persisitence is NFS dynamic provisioning and work correct)
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  security:
    tls:
      transport:
        generate: false
        perNode: false 
        secret:
          name: opensearch-cert
        caSecret:
          name: opensearch-ca-cert
      http:
        generate: false
        secret:
          name: opensearch-cert
        caSecret:
          name: opensearch-ca-cert 
  general:
    serviceName: opensearch-cluster
    version: 1.3.1
    setVMMaxMapCount: true
    additionalConfig:
      logger.level: "DEBUG"
      plugins.security.ssl.transport.enforce_hostname_verification: "false"
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "2Gi"
         cpu: "1000m"
    additionalConfig:
      opensearch_security.multitenancy.enabled: "true"
    tls:
      enable: true
      generate: false
      secret:
        name: opensearch-cert
      caSecret:
        name: opensearch-ca-cert 
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "16Gi"
      NodeSelector:
      resources:
         requests:
            memory: "6Gi"
            cpu: "200m"
         limits:
            memory: "6Gi"
            cpu: "1000m"
      roles:
        - "master"
        - "data"
      persistence:
        pvc:
          storageClass: managed-opensearch-storage
          accessModes:
            - ReadWriteOnce
    - component: coordinating
      replicas: 1
      diskSize: "8Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "6Gi"
            cpu: "2000m"
      roles:
        - "ingest"
      persistence:
        pvc:
          storageClass: managed-opensearch-storage
          accessModes:
          - ReadWriteOnce
    - component: warm
      replicas: 1
      diskSize: "16Gi"
      NodeSelector:
      resources:
         requests:
            memory: "4Gi"
            cpu: "500m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "data"
      additionalConfig:
        node.attr.temp: warm
      persistence:
        pvc:
          storageClass: managed-opensearch-storage-warm
          accessModes:
          - ReadWriteOnce
```

I've not set nodesDn cause i've added `subjectAltName=RID:1.2.3.4.5.5` in the certificate but i've also did a try without adding the RID and setup the correct nodesDn in the yaml but the results is the same with the same following error in the **coordinating pod** log with DEBUG activated
```
[2022-11-11T14:22:50,997][DEBUG][i.n.h.s.SslHandler       ] [opensearch-cluster-coordinating-0] [id: 0x9f9b2fa5, L:/127.0.0.1:9200 - R:/127.0.0.1:47732] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[2022-11-11T14:22:51,002][DEBUG][i.n.h.s.SslHandler       ] [opensearch-cluster-coordinating-0] [id: 0x9f9b2fa5, L:/127.0.0.1:9200 - R:/127.0.0.1:47732] Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
        at org.opensearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:155) ~[transport-netty4-client-1.3.1.jar:1.3.1]
        at org.opensearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:140) ~[transport-netty4-client-1.3.1.jar:1.3.1]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

The **bootstrap pod** has NO error in the logs.

The **master pod** and the **warm pod** has the same error with DEBUG activated
```
[2022-11-11T14:41:21,024][DEBUG][i.n.h.s.SslHandler       ] [opensearch-cluster-masters-0] [id: 0xae85788d, L:/127.0.0.1:9200 - R:/127.0.0.1:51024] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[2022-11-11T14:41:21,029][DEBUG][i.n.h.s.SslHandler       ] [opensearch-cluster-masters-0] [id: 0xae85788d, L:/127.0.0.1:9200 - R:/127.0.0.1:51024] Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
        at org.opensearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:155) ~[transport-netty4-client-1.3.1.jar:1.3.1]
        at org.opensearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:140) ~[transport-netty4-client-1.3.1.jar:1.3.1]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[2022-11-11T14:41:35,865][DEBUG][o.o.m.f.FsHealthService  ] [opensearch-cluster-masters-0] health check succeeded
```

**Comment by swoehrl-mw** [comment]
Hi @mastercrys.
When you provide your own certificates you also need to provide an admin cert for the operator to use (see https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#securityconfig: "If you provided your own certificate for node transport communication, then you must also provide an admin client certificate").

**Comment by mastercrys** [comment]
Hi @swoehrl-mw,
as suggested i've added the admin cert section in the config and can confirm that a security-config pod has added without any error in the log but the cluster remain in 0/1 state with the same error:
```
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
        at org.opensearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:155) ~[transport-netty4-client-1.3.1.jar:1.3.1]
        at org.opensearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:140) ~[transport-netty4-client-1.3.1.jar:1.3.1]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Note that we won't generate a different certificate for each node

**Comment by mastercrys** [comment]
For those who has similar issue, opensearch documentation about tls cert did not specify that the admin cert must be generated different from node cert. We have applied this script for cert generation
```
#!/bin/sh
# Root CA
openssl genrsa -out root-ca-key.pem 2048
openssl req -new -x509 -sha256 -key root-ca-key.pem -subj "/C=xx/ST=xxx/L=xxx/O=xxx/OU=xxx/CN=root" -out root-ca.pem -days 36500
# Admin cert
openssl genrsa -out admin-key-temp.pem 2048
openssl pkcs8 -inform PEM -outform PEM -in admin-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out admin-key.pem
openssl req -new -key admin-key.pem -subj "/CN=A" -out admin.csr
openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out admin.pem -days 36500
# Unique cert
openssl genrsa -out node-key-temp.pem 2048
openssl pkcs8 -inform PEM -outform PEM -in node-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out node-key.pem
openssl req -new -key node-key.pem -subj "/C=xx/ST=xxx/L=xxx/O=xxx/OU=xxx/CN=*opensearch-cluster*" -out node.csr
echo 'subjectAltName=RID:1.2.3.4.5.5,DNS:opensearch-cluster,DNS:opensearch-cluster.opensearch,DNS:opensearch-cluster.opensearch.svc,DNS:opensearch-cluster.opensearch.svc.cluster.local' > unique.ext
openssl x509 -req -in node.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out node.pem -days 36500 -extfile unique.ext
# Cleanup
rm admin-key-temp.pem
rm admin.csr
rm node-key-temp.pem
rm node.csr
rm admin.ext
rm unique.ext
# Add to k8s
kubectl delete secret opensearch-ca-cert
kubectl delete secret opensearch-cert
kubectl delete secret opensearch-admin-cert
kubectl create secret generic opensearch-ca-cert --from-file=ca.crt=root-ca.pem
kubectl create secret tls opensearch-cert --cert=node.pem --key=node-key.pem
kubectl create secret generic opensearch-admin-cert --from-file=ca.crt=root-ca.pem --from-file=tls.key=admin-key.pem --from-file=tls.crt=admin.pem
```

The security spec section in the opesearch operator yaml 
```
spec:
  security:
    tls:
      transport:
        generate: false
        perNode: false 
        secret:
          name: opensearch-cert
        caSecret:
          name: opensearch-ca-cert
        nodesDn: [ "CN=*opensearch-cluster*,OU=xxx,O=xxx,L=xxx,ST=xxx,C=xx" ]
        adminDn: [ "CN=A" ]
      http:
        generate: false
        secret:
          name: opensearch-cert
        caSecret:
          name: opensearch-ca-cert
    config:
      adminSecret:
        name: opensearch-admin-cert 
```

With this setup a new pod ***opensearch-cluster-securityconfig-update*** will start and when it's done the cluster starts working.
