### ISSUE TITLE
Issue exposing Node HTTP/REST API

### ISSUE THREAD

**Issue by jernster** [Opster/opensearch-k8s-operator#385]
I'm trying to expose the node HTTP/REST API port 9200 outside the cluster the same way I expose the dashboards service by pointing the service to a load balancer.  Setup is AWS EKS with aws load balancer controller.

If I set any of these parameters to false, the cluster doesn't deploy:

```
spec:
  security:
    config:
    tls:
       http:
         generate: true
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9200
    serviceName: dl-opensearch-1-svc
    version: 2.3.0
    pluginsList: ["repository-s3"]
    drainDataNodes: true
```

But if I deploy the cluster as is and modify the service to point to the network load balancer (which hosts the TLS certificate) and access the endpoint, the master logs show the following errors:

```
[2022-12-06T23:09:57,119][ERROR][o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport] [dl-opensearch-1-masters-0] Exception during establishing a SSL connection: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a486f73743a206f70656e7365617263682d696e67726573732d316135623465623430623038376166352e656c622e75732d656173742d312e616d617a6f6e6177732e636f6d3a393230300d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a43616368652d436f6e74726f6c3a206d61782d6167653d300d0a7365632d63682d75613a2022476f6f676c65204368726f6d65223b763d22313037222c20224368726f6d69756d223b763d22313037222c20224e6f743d413f4272616e64223b763d223234220d0a7365632d63682d75612d6d6f62696c653a203f300d0a7365632d63682d75612d706c6174666f726d3a202257696e646f7773220d0a557067726164652d496e7365637572652d52657175657374733a20310d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e542031302e303b2057696e36343b2078363429204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f29204368726f6d652f3130372e302e302e30205361666172692f3533372e33360d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c696d6167652f617669662c696d6167652f776562702c696d6167652f61706e672c2a2f2a3b713d302e382c6170706c69636174696f6e2f7369676e65642d65786368616e67653b763d62333b713d302e390d0a5365632d46657463682d536974653a206e6f6e650d0a5365632d46657463682d4d6f64653a206e617669676174650d0a5365632d46657463682d557365723a203f310d0a5365632d46657463682d446573743a20646f63756d656e740d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062720d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e390d0a0d0a
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a486f73743a206f70656e7365617263682d696e67726573732d316135623465623430623038376166352e656c622e75732d656173742d312e616d617a6f6e6177732e636f6d3a393230300d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a43616368652d436f6e74726f6c3a206d61782d6167653d300d0a7365632d63682d75613a2022476f6f676c65204368726f6d65223b763d22313037222c20224368726f6d69756d223b763d22313037222c20224e6f743d413f4272616e64223b763d223234220d0a7365632d63682d75612d6d6f62696c653a203f300d0a7365632d63682d75612d706c6174666f726d3a202257696e646f7773220d0a557067726164652d496e7365637572652d52657175657374733a20310d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e542031302e303b2057696e36343b2078363429204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f29204368726f6d652f3130372e302e302e30205361666172692f3533372e33360d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c696d6167652f617669662c696d6167652f776562702c696d6167652f61706e672c2a2f2a3b713d302e382c6170706c69636174696f6e2f7369676e65642d65786368616e67653b763d62333b713d302e390d0a5365632d46657463682d536974653a206e6f6e650d0a5365632d46657463682d4d6f64653a206e617669676174650d0a5365632d46657463682d557365723a203f310d0a5365632d46657463682d446573743a20646f63756d656e740d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c2062720d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e390d0a0d0a
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1215) ~[netty-handler-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.79.Final.jar:4.1.79.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
	
It would seem at the very least one should be able to set this to false, but provision the other internal self signed certs.

```
  security:
    config:
    tls:
       http:
         generate: true
```

Is there any way to accomplish this?  I was able to do this for the dashboards with no issues:

```
  dashboards:
    tls:
      enable: false
      generate: false
    version: 2.3.0
```

Thanks

**Comment by swoehrl-mw** [comment]
Hi @jernster. Do I understand correctly that you want to do TLS termination in the AWS loadbalancer and use an unencrypted connection between the loadbalancer and opensearch?

That is not possible with the operator. You cannot disable TLS for opensearch. As such any loadbalancer or ingress you deploy in front of opensearch must always use HTTPS to talk to opensearch.

**Comment by jernster** [comment]
Hi @swoehrl-mw 

It seems the key part of the documentation is this:

Directly exposing the node HTTP port outside the Kubernetes cluster is not recommended. Rather than doing so, you should configure an ingress. The ingress can then also present a certificate from an accredited CA (for example LetsEncrypt) and hide self-signed certificates that are being used internally. In this way, the nodes should be supplied internally with properly signed certificates.

It seems I am doing this by creating the nlb as the ingress.

I don't want to provide my own certificates inside the cluster because it's eks, the host names are unique and can change frequently.  The nlb hosts a certificate with a SAN that I want to represent as the http/rest hostname, and is communicating to opensearch over TLS as shown here:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/9053623/206530622-d0f0f3c1-6fa7-4c57-9eb3-dfdb1178b687.png">

Ultimately we want to expose the http/rest api so we're able to issue curl commands and such outside of the dashboards, or for apps that might need to communicate with the cluster outside kubernetes.

**Comment by swoehrl-mw** [comment]
@jernster Can you please share the (complete) service/ingress definition you are using to expose opensearch along with your opensearch cluster yaml?

> I don't want to provide my own certificates inside the cluster because it's eks

That is why the operator can generate self-signed certificates for internal communication so you don't need to provide them. These use the pod names, so are stable. Your own certificate only comes into play at the ingress/Loadbalancer level.

**Comment by swoehrl-mw** [comment]
Hi @jernster. I believe you are missing the annotation to tell the loadbalancer to speak https to its pods:
`service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https`
(as described [in the k8s loadbalancer docs](https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws)).
You might run into another problem if the NLB needs to verify the cert of the pod, but I'm not deep enough into EKS and NLB to know how to configure that (that option is often called along the lines of insecure verification).

Another point: Did you edit the Service object as created by the operator? That is not a good idea as that can be overwritten any time by the operator. Instead you should create your own Service object so it does not get overwritten by the operator.

**Comment by jernster** [comment]
Hi @swoehrl-mw,

Something like this?  This contains all the modifications I'm making when I edit the service directly - everything else should just be there from when the cluster is provisioned.

FYI the contents below creates a working nlb load balancer which solves the issue which sparked creation of the issue.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-name: opensearch-ingress
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9200"
    service.beta.kubernetes.io/aws-load-balancer-type: external
  name: dl-opensearch-1-svc
  namespace: opensearch
spec:
  type: LoadBalancer
```



Interestingly it doesn't create any listeners at all, but creates the functionality I need and uses the certificate specified.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/9053623/207466679-bd66fcbb-5497-4d21-b55c-94c162061941.png">

The thing with just applying this service manifest (assuming the service is in the state it is after initial deployment) is that the service still needs to be edited to change the ClusterIP to LoadBalancer after it actually completes provisioning.  It adds this part to the service as soon as it's applied the first time, but the type doesn't update on its own automatically, so the service needs to be manually edited, or the manifest needs to be re-applied after the load balancer finishes provisioning.

```
status:
  loadBalancer:
    ingress:
    - hostname: xxx.amazonaws.com
```

**Comment by swoehrl-mw** [comment]
> FYI the contents below creates a working nlb load balancer which solves the issue which sparked creation of the issue.

Good to hear. Can we consider this issue resolved?

> The thing with just applying this service manifest [...]

To clarify: You are applying this service manifest over the one created by the operator (which creates a type ClusterIP)?
As I stated before, please use a separate service (e.g. named `dl-opensearch-1-lb`). That way you are not influenced by what the operator does to its service and because you create it with the correct type in the first place there should be no problems with an incomplete change as you described either.

**Comment by jernster** [comment]
> To clarify: You are applying this service manifest over the one created by the operator (which creates a type ClusterIP)? As I stated before, please use a separate service (e.g. named `dl-opensearch-1-lb`). That way you are not influenced by what the operator does to its service and because you create it with the correct type in the first place there should be no problems with an incomplete change as you described either.

Would this not create some sort of conflict with the existing service though?

It would essentially duplicate this part:

```
  ports:
  - name: http
    nodePort: 31921
    port: 9200
    protocol: TCP
    targetPort: 9200
```

**Comment by swoehrl-mw** [comment]
> Would this not create some sort of conflict with the existing service though?

Each service is independent of others, so you can have the same ports. It is no problem to have a service of type ClusterIP and one of type Loadbalancer to point to the same pods and have the same ports, they will not be in conflict.
