### ISSUE TITLE
operator doesn't update image version while upgrading a cluster

### ISSUE THREAD

**Issue by deng47** [Opster/opensearch-k8s-operator#420]
I deployed an Opensearch v2.4.1 with opensearch-operator-2.1.1
Then I tried to upgrade the cluster to v.2.5.0 by changing the spec.general.version(and plugin version as well)
Changed from
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-system
  namespace: my-system
spec:
  general:
    version: "2.4.1"
    httpPort: 9200
    vendor: opensearch
    serviceName: my-system
    pluginsList: ["repository-s3", "https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.4.1.0/prometheus-exporter-2.4.1.0.zip"]
<SKIP THE REST>
```
To
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-system
  namespace: my-system
spec:
  general:
    version: "2.5.0"
    httpPort: 9200
    vendor: opensearch
    serviceName: my-system
    pluginsList: ["repository-s3", "https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.5.0.0/prometheus-exporter-2.5.0.0.zip"]
<SKIP THE REST>
```
Data nodes got upgraded to v2.5.0 after apply the yaml file. But new master nodes and client nodes failed to boot up with errors below 
```
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [prometheus-exporter] was built for OpenSearch version 2.5.0 but version 2.4.1 is running
	at org.opensearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:394)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:820)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```
Pod events show it's still pulling the v2.4.1 image
```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  3m57s                   default-scheduler  Successfully assigned my-system/my-system-masters-2 to host3
  Normal   Pulled     3m56s                   kubelet            Container image "public.ecr.aws/opsterio/busybox:1.27.2-buildx" already present on machine
  Normal   Created    3m56s                   kubelet            Created container init
  Normal   Started    3m56s                   kubelet            Started container init
  Normal   Pulled     3m2s (x4 over 3m56s)    kubelet            Container image "docker.io/opensearchproject/opensearch:2.4.1" already present on machine
  Normal   Created    3m2s (x4 over 3m56s)    kubelet            Created container opensearch
  Normal   Started    3m2s (x4 over 3m55s)    kubelet            Started container opensearch
  Warning  BackOff    2m27s (x10 over 3m48s)  kubelet            Back-off restarting failed container
```
Pod description shows it uses v2.4.1 as well
```
Containers:
  opensearch:
    Container ID:  containerd://743950cfdef64a76f394416a6a51e9277a610cd5f58cb45b44d281b40e3a8e8a
    Image:         docker.io/opensearchproject/opensearch:2.4.1
```

**Comment by arve0** [comment]
Related: https://github.com/Opster/opensearch-k8s-operator/issues/404

**Comment by swoehrl-mw** [comment]
I was able to reproduce this. Looks like the operator starts with the upgrade of the data nodes but somehow at the same time starts a rolling restart of the master nodes due to the changed plugin which then fails due to old image version and new plugin version. Seems the operator is not correctly checking for upgrade-in-progress before starting the rolling restart. Not yet sure where in the code exactly and how to fix it.

As a workaround: For me it worked to wait until the data nodes were finished upgrading and then manually delete (`kubectl delete pod`) the crashing pods. After that the operator continued with the upgrade as expected.

**Comment by deng47** [comment]
Thank you @swoehrl-mw but the workaround doesn't work for me. I upgraded the operator to 2.2.0, and then all data node to 2.5.0, tried deleting master and client pods that are in a CrashLoopBackOff state. But they still use the OS v2.4.1 image and try to install a v2.5.0 exporter plugin(I need this plugin), so they stuck in CrashLoopBackOff

**Comment by swoehrl-mw** [comment]
Did some more testing and found the problem: Non-data nodepools are not upgraded by the operator bust it instead delegates that to the statefulset controller of Kubernetes. This lead to the pods being recreated prematurely with a half-old-half-new config (old docker image, new plugin version) and subsequently to the crashes. That also got the operator into an unexpected state, so the upgrade stalled.

I've created a PR (#431) that should fix the problem.
