### ISSUE TITLE
Tracing and observability menus return errors or stuck on white screen

### ISSUE THREAD

**Issue by lazarevdmitriy** [Opster/opensearch-k8s-operator#588]
Сhart_version         = "2.3.1"
OpenSearchCluster version = 2.8.0
OpenSearch Dashboards version = 2.8.0

Trying to create a new visualization in the dashboard return the error  "Unable to get default timestamp"
`TypeError: Cannot read properties of undefined (reading 'toastMessage')
    at ToastsApi.addError (https://l0g.invent.us/6182/bundles/core/core.entry.js:15:635096)
    at PPLDataFetcher._callee$ (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.4.js:1:7463)
    at tryCatch (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.3.js:625:70469)
    at Generator.invoke [as _invoke] (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.3.js:625:74485)
    at Generator.next (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.3.js:625:71664)
    at asyncGeneratorStep (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.4.js:1:2978)
    at _next (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.4.js:1:3289)`
    
If you go to a specific trace.  To the span list. Click on the span id - an empty window appears. There is an error in the chrome debugging console:
`osd-ui-shared-deps.js:436 TypeError: Cannot read properties of undefined (reading 'error')
    at renderContent (observabilityDashboards.plugin.js:1745:77228)
    at SpanDetailFlyout (observabilityDashboards.plugin.js:1745:80956)
    at Yo (osd-ui-shared-deps.js:436:57931)
    at Na (osd-ui-shared-deps.js:436:66792)
    at gs (osd-ui-shared-deps.js:436:105389)
    at uc (osd-ui-shared-deps.js:436:96718)
    at sc (osd-ui-shared-deps.js:436:96643)
    at Qs (osd-ui-shared-deps.js:436:93673)
    at osd-ui-shared-deps.js:436:45315
    at t.unstable_runWithPriority (osd-ui-shared-deps.js:444:3844)
es @ osd-ui-shared-deps.js:436
n.callback @ osd-ui-shared-deps.js:436
po @ osd-ui-shared-deps.js:436
os @ osd-ui-shared-deps.js:436
fc @ osd-ui-shared-deps.js:436
t.unstable_runWithPriority @ osd-ui-shared-deps.js:444
ji @ osd-ui-shared-deps.js:436
dc @ osd-ui-shared-deps.js:436
Qs @ osd-ui-shared-deps.js:436
(anonymous) @ osd-ui-shared-deps.js:436
t.unstable_runWithPriority @ osd-ui-shared-deps.js:444
ji @ osd-ui-shared-deps.js:436
Ui @ osd-ui-shared-deps.js:436
Hi @ osd-ui-shared-deps.js:436
Ys @ osd-ui-shared-deps.js:436
ba @ osd-ui-shared-deps.js:436
(anonymous) @ observabilityDashboards.plugin.js:1540
Promise.then (async)
handleSpansFlyoutRequest @ observabilityDashboards.plugin.js:1540
(anonymous) @ observabilityDashboards.plugin.js:1745
is @ osd-ui-shared-deps.js:436
gc @ osd-ui-shared-deps.js:436
t.unstable_runWithPriority @ osd-ui-shared-deps.js:444
ji @ osd-ui-shared-deps.js:436
bc @ osd-ui-shared-deps.js:436
(anonymous) @ osd-ui-shared-deps.js:436
P @ osd-ui-shared-deps.js:444
_.port1.onmessage @ osd-ui-shared-deps.js:444
`

Сonfig where I can reproduce that:
[https://github.com/lazarevdmitriy/images/blob/main/opensearch-cluster.yaml](url)

**Comment by swoehrl-mw** [comment]
Hi @lazarevdmitriy. This sounds more like a problem with Dashboards than with the operator in particular. I suggest you use the [Opensearch Forum](https://forum.opensearch.org/) to get help.
