### ISSUE TITLE
OMC backend is failing when general.imagePullSecrets is set to []

### ISSUE THREAD

**Issue by evheniyt** [Opster/opensearch-k8s-operator#632]
OMC backend pod is throwing an exception when `general.imagePullSecrets` is set to []
```
general:
  imagePullSecrets: []
```
The cluster itself works fine with this configuration.

Part of the exception:
```
management-console-be Caused by: java.lang.IllegalArgumentException: Cannot deserialize value of type `io.kubernetes.client.openapi.models.V1LocalObjectReference` from Array value (token `JsonToken.START_ARRAY`) 
management-console-be  at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.opster.k8operator.model.kubernetes.V1CRDList["items"]->java.util.ArrayList[0]->com.opster.k8operator.model.kubernet
es.V1CRDItem["spec"]->com.opster.k8operator.model.kubernetes.operator.OperatorCrdInstance["general"]->com.opster.k8operator.model.kubernetes.operator.OperatorGeneralConfiguration["imagePullSecrets"])             
management-console-be     at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393) ~[jackson-databind-2.13.3.jar!/:2.13.3]                                                                   
management-console-be     at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4334) ~[jackson-databind-2.13.3.jar!/:2.13.3]                                                               
management-console-be     at com.opster.k8operator.json.JsonUtils.fromJsonObject(JsonUtils.java:93) ~[json-0.1.jar!/:0.1]                                                                                           
management-console-be     ... 114 common frames omitted                                                                                                                                                             
management-console-be Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `io.kubernetes.client.openapi.models.V1LocalObjectReference` from Array value (token 
`JsonToken.START_ARRAY`)   
```
It only fails on `general.imagePullSecrets`, rest of configuration sections where we have `imagePullSecrets: []` works fine.

When we removed `general.imagePullSecrets` from configuration OMC started working as expected.

OpenSearch version 1.3.13
Operator version 2.4.0

**Comment by swoehrl-mw** [comment]
OMC is not part of the operator, issues for it will not be tracked in this project. Please contact Opster directly.
